spring:
  datasource:
    driver-class-name:  org.sqlite.JDBC
    url:  jdbc:sqlite::resource:db/mylite4.db
    username: root
    password: 988988aa

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/southwind/mapper/xml/*.xml
server:
  port: 8181
